### PR TITLE
rough 0.0.1

### PR DESCRIPTION
**Pull request by wommy**
lots 2 do

### CODE REVIEW

**Comment by ZoeBijl** [comment]
Anything I should know about SugarSS? I'm not familiar with it, but anything that compiles to css works for me.

**Comment by Synj24** [comment]
Its white space sensitive. (hence the name)
It usually complains at compile time if it doesn't like something (e.g. mix of spaces and tabs) so its pretty straight forward to see if something isn't right.
oh and no semi colons :slightly_smiling_face: 

heres the repo:
https://github.com/postcss/sugarss

**Comment by jonathantneal** [comment]
Thanks for the PR. I’ll check it out now.

As far as pseudo languages go, we’ll use standards-track HTML, CSS, and JS. We have a preset-env for babel and postcss to give us code _more likely_ to be known, understood, and even adopted someday by other contributors.

**Comment by jonathantneal** [comment]
I’ve merged the others. This had conflicts.

**Pull request closed without merging**
